# Generated by Django 4.0.5 on 2022-06-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userform',
            old_name='dics',
            new_name='disc',
        ),
    ]
