# Generated by Django 4.0.4 on 2022-07-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_dics_userform_disc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupform',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
